import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import StyledComponentsRegistry from '@/context/AntdRegistry'
import Header from '@/components/Header'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="bg-[#f1f1f3] text-gray-900 w-full">
      <body className={`${openSans.className}`}>
        <Header />
        {/* <StyledComponentsRegistry> */}
        <main className="w-full mx-auto max-w-[1200px] mt-8">{children}</main>
        {/* </StyledComponentsRegistry> */}
      </body>
    </html>
  )
}
